# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T02:21:07+00:00

from __future__ import annotations

from enum import Enum
from typing import List, Optional

from pydantic import BaseModel, Field


class Attachment(BaseModel):
    mimeType: Optional[List[str]] = Field(
        None,
        description='The MIME types (IANA media types) in which the attachment is available.',
    )
    name: Optional[str] = Field(None, description='The resource name;')


class BatchDeletePermissionsRequest(BaseModel):
    names: Optional[List[str]] = Field(
        None,
        description='Required. The names of the permissions to delete. Format: `notes/{note}/permissions/{permission}`',
    )


class Empty(BaseModel):
    pass


class Family(BaseModel):
    pass


class Group(BaseModel):
    email: Optional[str] = Field(None, description='The group email.')


class Role(Enum):
    ROLE_UNSPECIFIED = 'ROLE_UNSPECIFIED'
    OWNER = 'OWNER'
    WRITER = 'WRITER'


class TextContent(BaseModel):
    text: Optional[str] = Field(
        None,
        description='The text of the note. The limits on this vary with the specific field using this type.',
    )


class User(BaseModel):
    email: Optional[str] = Field(None, description="The user's email.")


class FieldXgafv(Enum):
    field_1 = '1'
    field_2 = '2'


class Alt(Enum):
    json = 'json'
    media = 'media'
    proto = 'proto'


class ListItem(BaseModel):
    checked: Optional[bool] = Field(
        None, description='Whether this item has been checked off or not.'
    )
    childListItems: Optional[List[ListItem]] = Field(
        None,
        description='If set, list of list items nested under this list item. Only one level of nesting is allowed.',
    )
    text: Optional[TextContent] = Field(
        None,
        description='The text of this item. Length must be less than 1,000 characters.',
    )


class Permission(BaseModel):
    deleted: Optional[bool] = Field(
        None,
        description='Output only. Whether this member has been deleted. If the member is recovered, this value is set to false and the recovered member retains the role on the note.',
    )
    email: Optional[str] = Field(
        None,
        description='The email associated with the member. If set on create, the `email` field in the `User` or `Group` message must either be empty or match this field. On read, may be unset if the member does not have an associated email.',
    )
    family: Optional[Family] = Field(
        None, description='Output only. The Google Family to which this role applies.'
    )
    group: Optional[Group] = Field(
        None, description='Output only. The group to which this role applies.'
    )
    name: Optional[str] = Field(None, description='Output only. The resource name.')
    role: Optional[Role] = Field(
        None,
        description='The role granted by this permission. The role determines the entity’s ability to read, write, and share notes.',
    )
    user: Optional[User] = Field(
        None, description='Output only. The user to whom this role applies.'
    )


class BatchCreatePermissionsResponse(BaseModel):
    permissions: Optional[List[Permission]] = Field(
        None, description='Permissions created.'
    )


class CreatePermissionRequest(BaseModel):
    parent: Optional[str] = Field(
        None,
        description='Required. The parent note where this permission will be created. Format: `notes/{note}`',
    )
    permission: Optional[Permission] = Field(
        None,
        description='Required. The permission to create. One of Permission.email, User.email or Group.email must be supplied.',
    )


class ListContent(BaseModel):
    listItems: Optional[List[ListItem]] = Field(
        None,
        description='The items in the list. The number of items must be less than 1,000.',
    )


class Section(BaseModel):
    list: Optional[ListContent] = Field(
        None, description="Used if this section's content is a list."
    )
    text: Optional[TextContent] = Field(
        None,
        description="Used if this section's content is a block of text. The length of the text content must be less than 20,000 characters.",
    )


class BatchCreatePermissionsRequest(BaseModel):
    requests: Optional[List[CreatePermissionRequest]] = Field(
        None, description='The request message specifying the resources to create.'
    )


class Note(BaseModel):
    attachments: Optional[List[Attachment]] = Field(
        None, description='Output only. The attachments attached to this note.'
    )
    body: Optional[Section] = Field(None, description='The body of the note.')
    createTime: Optional[str] = Field(
        None, description='Output only. When this note was created.'
    )
    name: Optional[str] = Field(
        None,
        description='Output only. The resource name of this note. See general note on identifiers in KeepService.',
    )
    permissions: Optional[List[Permission]] = Field(
        None,
        description='Output only. The list of permissions set on the note. Contains at least one entry for the note owner.',
    )
    title: Optional[str] = Field(
        None,
        description='The title of the note. Length must be less than 1,000 characters.',
    )
    trashTime: Optional[str] = Field(
        None,
        description='Output only. When this note was trashed. If `trashed`, the note is eventually deleted. If the note is not trashed, this field is not set (and the trashed field is `false`).',
    )
    trashed: Optional[bool] = Field(
        None,
        description='Output only. `true` if this note has been trashed. If trashed, the note is eventually deleted.',
    )
    updateTime: Optional[str] = Field(
        None, description='Output only. When this note was last modified.'
    )


class ListNotesResponse(BaseModel):
    nextPageToken: Optional[str] = Field(
        None, description="Next page's `page_token` field."
    )
    notes: Optional[List[Note]] = Field(None, description='A page of notes.')


ListItem.model_rebuild()
